### ISSUE TITLE
Prevent new content from being created with a trailing period (.) in the route

### ISSUE THREAD

**Issue by mattbostock** [alphagov/publishing-api#166]
__As a__ user with a letter from the government containing a URL
__I want__ to be able to type that URL as I see it
__So that__ I can get to the page I am looking for

"As a Core team member I want to implement a rule whereby if a user adds a full stop to the end of the URL (most likely because they are sent a printed letter that shows the URL at the end of a sentence and therefore with a '.' appended) that the full stop is automatically stripped out so that the user does not see a 404."

Over 6 months 107,000 404s were URLs ending in a full stop. This is about 3% of all 404s recorded during this time frame. A small % of the overall number, but still a significant number of errors. Implementing this change would address the bulk of these URL problems, though they could contain other issues that we can't see from the report.

A letter will be going out soon to 4m people which will include a link at the end of a sentence.

We're [now automatically redirecting all URLs containing a trailing period](https://github.gds/gds/puppet/pull/3603) in Varnish, having ascertained that no content legitimately uses one, so we should ensure that new content cannot be created with a trailing period in its route.

**Comment by elliotcm** [comment]
This is being added as a ticket to our future cleanup work.
